spring:
  datasource:
    url: jdbc:sqlserver://localhost:50271;databaseName=Bank;encrypt=true;trustServerCertificate=true;
    username: your_db_username
    password: your_db_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect

